[env:esp32s3_custom]
platform = espressif32
; 1. Mude para uma placa genérica como base
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; 2. Force as configurações de hardware CORRETAS (vistas no log)
board_build.flash_size = 8MB
board_build.flash_mode = qio
board_build.flash_freq = 80m
; 3. Use uma tabela de partição padrão de 8MB (sem PSRAM)
board_build.partitions = default_8mb.csv

build_unflags = -std=gnu++11

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -std=gnu++17
; flag para o TFLM funcionar
  -fexceptions
build_type = release
lib_deps = 
  ottowinter/ESPAsyncWebServer-esphome
  marvinroger/AsyncMqttClient
  bblanchon/ArduinoJson
  madhephaestus/ESP32Servo
  
  ; TensorFlow Lite for Microcontrollers
  git+https://github.com/tanakamasayuki/Arduino_TensorFlowLite_ESP32.git